package com.btjf.mapper;

import com.btjf.model.EvaluateLabel;
import com.btjf.model.EvaluateLabelExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EvaluateLabelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_evaluate_label
     *
     * @mbg.generated
     */
    long countByExample(EvaluateLabelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_evaluate_label
     *
     * @mbg.generated
     */
    int deleteByExample(EvaluateLabelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_evaluate_label
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer ID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_evaluate_label
     *
     * @mbg.generated
     */
    int insert(EvaluateLabel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_evaluate_label
     *
     * @mbg.generated
     */
    int insertSelective(EvaluateLabel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_evaluate_label
     *
     * @mbg.generated
     */
    List<EvaluateLabel> selectByExample(EvaluateLabelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_evaluate_label
     *
     * @mbg.generated
     */
    EvaluateLabel selectByPrimaryKey(Integer ID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_evaluate_label
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") EvaluateLabel record, @Param("example") EvaluateLabelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_evaluate_label
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") EvaluateLabel record, @Param("example") EvaluateLabelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_evaluate_label
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(EvaluateLabel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_evaluate_label
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(EvaluateLabel record);
}