package com.btjf.mapper;

import com.btjf.model.Evaluate;
import com.btjf.model.EvaluateExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EvaluateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_evaluate
     *
     * @mbg.generated
     */
    long countByExample(EvaluateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_evaluate
     *
     * @mbg.generated
     */
    int deleteByExample(EvaluateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_evaluate
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer ID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_evaluate
     *
     * @mbg.generated
     */
    int insert(Evaluate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_evaluate
     *
     * @mbg.generated
     */
    int insertSelective(Evaluate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_evaluate
     *
     * @mbg.generated
     */
    List<Evaluate> selectByExample(EvaluateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_evaluate
     *
     * @mbg.generated
     */
    Evaluate selectByPrimaryKey(Integer ID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_evaluate
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Evaluate record, @Param("example") EvaluateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_evaluate
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Evaluate record, @Param("example") EvaluateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_evaluate
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Evaluate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_evaluate
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Evaluate record);

    Double averageScore(@Param("staffID") String staffID);

    Double averageTime(@Param("staffID") String staffID);

    List<String> getLabels(@Param("staffID")String staffID);
}