package com.btjf.model;

import java.io.Serializable;
import java.util.Date;

public class Evaluate implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_evaluate.FID
     *
     * @mbg.generated
     */
    private Integer ID;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_evaluate.FDeptID
     *
     * @mbg.generated
     */
    private Integer deptID;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_evaluate.FDeptName
     *
     * @mbg.generated
     */
    private String deptName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_evaluate.FWindowNo
     *
     * @mbg.generated
     */
    private Integer windowNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_evaluate.FStaffID
     *
     * @mbg.generated
     */
    private Integer staffID;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_evaluate.FStaffName
     *
     * @mbg.generated
     */
    private String staffName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_evaluate.FCustName
     *
     * @mbg.generated
     */
    private String custName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_evaluate.FCustMobile
     *
     * @mbg.generated
     */
    private String custMobile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_evaluate.FItemID
     *
     * @mbg.generated
     */
    private Integer itemID;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_evaluate.FItemName
     *
     * @mbg.generated
     */
    private String itemName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_evaluate.FCreateDate
     *
     * @mbg.generated
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_evaluate.FBeginTime
     *
     * @mbg.generated
     */
    private Date beginTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_evaluate.FEndTime
     *
     * @mbg.generated
     */
    private Date endTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_evaluate.FDuration
     *
     * @mbg.generated
     */
    private Integer duration;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_evaluate.FQuestion
     *
     * @mbg.generated
     */
    private String question;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_evaluate.FAnswer
     *
     * @mbg.generated
     */
    private Integer answer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_evaluate.FEvaluate
     *
     * @mbg.generated
     */
    private Integer evaluate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_evaluate
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_evaluate.FID
     *
     * @return the value of t_evaluate.FID
     *
     * @mbg.generated
     */
    public Integer getID() {
        return ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_evaluate.FID
     *
     * @param ID the value for t_evaluate.FID
     *
     * @mbg.generated
     */
    public void setID(Integer ID) {
        this.ID = ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_evaluate.FDeptID
     *
     * @return the value of t_evaluate.FDeptID
     *
     * @mbg.generated
     */
    public Integer getDeptID() {
        return deptID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_evaluate.FDeptID
     *
     * @param deptID the value for t_evaluate.FDeptID
     *
     * @mbg.generated
     */
    public void setDeptID(Integer deptID) {
        this.deptID = deptID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_evaluate.FDeptName
     *
     * @return the value of t_evaluate.FDeptName
     *
     * @mbg.generated
     */
    public String getDeptName() {
        return deptName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_evaluate.FDeptName
     *
     * @param deptName the value for t_evaluate.FDeptName
     *
     * @mbg.generated
     */
    public void setDeptName(String deptName) {
        this.deptName = deptName == null ? null : deptName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_evaluate.FWindowNo
     *
     * @return the value of t_evaluate.FWindowNo
     *
     * @mbg.generated
     */
    public Integer getWindowNo() {
        return windowNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_evaluate.FWindowNo
     *
     * @param windowNo the value for t_evaluate.FWindowNo
     *
     * @mbg.generated
     */
    public void setWindowNo(Integer windowNo) {
        this.windowNo = windowNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_evaluate.FStaffID
     *
     * @return the value of t_evaluate.FStaffID
     *
     * @mbg.generated
     */
    public Integer getStaffID() {
        return staffID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_evaluate.FStaffID
     *
     * @param staffID the value for t_evaluate.FStaffID
     *
     * @mbg.generated
     */
    public void setStaffID(Integer staffID) {
        this.staffID = staffID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_evaluate.FStaffName
     *
     * @return the value of t_evaluate.FStaffName
     *
     * @mbg.generated
     */
    public String getStaffName() {
        return staffName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_evaluate.FStaffName
     *
     * @param staffName the value for t_evaluate.FStaffName
     *
     * @mbg.generated
     */
    public void setStaffName(String staffName) {
        this.staffName = staffName == null ? null : staffName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_evaluate.FCustName
     *
     * @return the value of t_evaluate.FCustName
     *
     * @mbg.generated
     */
    public String getCustName() {
        return custName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_evaluate.FCustName
     *
     * @param custName the value for t_evaluate.FCustName
     *
     * @mbg.generated
     */
    public void setCustName(String custName) {
        this.custName = custName == null ? null : custName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_evaluate.FCustMobile
     *
     * @return the value of t_evaluate.FCustMobile
     *
     * @mbg.generated
     */
    public String getCustMobile() {
        return custMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_evaluate.FCustMobile
     *
     * @param custMobile the value for t_evaluate.FCustMobile
     *
     * @mbg.generated
     */
    public void setCustMobile(String custMobile) {
        this.custMobile = custMobile == null ? null : custMobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_evaluate.FItemID
     *
     * @return the value of t_evaluate.FItemID
     *
     * @mbg.generated
     */
    public Integer getItemID() {
        return itemID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_evaluate.FItemID
     *
     * @param itemID the value for t_evaluate.FItemID
     *
     * @mbg.generated
     */
    public void setItemID(Integer itemID) {
        this.itemID = itemID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_evaluate.FItemName
     *
     * @return the value of t_evaluate.FItemName
     *
     * @mbg.generated
     */
    public String getItemName() {
        return itemName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_evaluate.FItemName
     *
     * @param itemName the value for t_evaluate.FItemName
     *
     * @mbg.generated
     */
    public void setItemName(String itemName) {
        this.itemName = itemName == null ? null : itemName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_evaluate.FCreateDate
     *
     * @return the value of t_evaluate.FCreateDate
     *
     * @mbg.generated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_evaluate.FCreateDate
     *
     * @param createDate the value for t_evaluate.FCreateDate
     *
     * @mbg.generated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_evaluate.FBeginTime
     *
     * @return the value of t_evaluate.FBeginTime
     *
     * @mbg.generated
     */
    public Date getBeginTime() {
        return beginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_evaluate.FBeginTime
     *
     * @param beginTime the value for t_evaluate.FBeginTime
     *
     * @mbg.generated
     */
    public void setBeginTime(Date beginTime) {
        this.beginTime = beginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_evaluate.FEndTime
     *
     * @return the value of t_evaluate.FEndTime
     *
     * @mbg.generated
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_evaluate.FEndTime
     *
     * @param endTime the value for t_evaluate.FEndTime
     *
     * @mbg.generated
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_evaluate.FDuration
     *
     * @return the value of t_evaluate.FDuration
     *
     * @mbg.generated
     */
    public Integer getDuration() {
        return duration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_evaluate.FDuration
     *
     * @param duration the value for t_evaluate.FDuration
     *
     * @mbg.generated
     */
    public void setDuration(Integer duration) {
        this.duration = duration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_evaluate.FQuestion
     *
     * @return the value of t_evaluate.FQuestion
     *
     * @mbg.generated
     */
    public String getQuestion() {
        return question;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_evaluate.FQuestion
     *
     * @param question the value for t_evaluate.FQuestion
     *
     * @mbg.generated
     */
    public void setQuestion(String question) {
        this.question = question == null ? null : question.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_evaluate.FAnswer
     *
     * @return the value of t_evaluate.FAnswer
     *
     * @mbg.generated
     */
    public Integer getAnswer() {
        return answer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_evaluate.FAnswer
     *
     * @param answer the value for t_evaluate.FAnswer
     *
     * @mbg.generated
     */
    public void setAnswer(Integer answer) {
        this.answer = answer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_evaluate.FEvaluate
     *
     * @return the value of t_evaluate.FEvaluate
     *
     * @mbg.generated
     */
    public Integer getEvaluate() {
        return evaluate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_evaluate.FEvaluate
     *
     * @param evaluate the value for t_evaluate.FEvaluate
     *
     * @mbg.generated
     */
    public void setEvaluate(Integer evaluate) {
        this.evaluate = evaluate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_evaluate
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Evaluate other = (Evaluate) that;
        return (this.getID() == null ? other.getID() == null : this.getID().equals(other.getID()))
            && (this.getDeptID() == null ? other.getDeptID() == null : this.getDeptID().equals(other.getDeptID()))
            && (this.getDeptName() == null ? other.getDeptName() == null : this.getDeptName().equals(other.getDeptName()))
            && (this.getWindowNo() == null ? other.getWindowNo() == null : this.getWindowNo().equals(other.getWindowNo()))
            && (this.getStaffID() == null ? other.getStaffID() == null : this.getStaffID().equals(other.getStaffID()))
            && (this.getStaffName() == null ? other.getStaffName() == null : this.getStaffName().equals(other.getStaffName()))
            && (this.getCustName() == null ? other.getCustName() == null : this.getCustName().equals(other.getCustName()))
            && (this.getCustMobile() == null ? other.getCustMobile() == null : this.getCustMobile().equals(other.getCustMobile()))
            && (this.getItemID() == null ? other.getItemID() == null : this.getItemID().equals(other.getItemID()))
            && (this.getItemName() == null ? other.getItemName() == null : this.getItemName().equals(other.getItemName()))
            && (this.getCreateDate() == null ? other.getCreateDate() == null : this.getCreateDate().equals(other.getCreateDate()))
            && (this.getBeginTime() == null ? other.getBeginTime() == null : this.getBeginTime().equals(other.getBeginTime()))
            && (this.getEndTime() == null ? other.getEndTime() == null : this.getEndTime().equals(other.getEndTime()))
            && (this.getDuration() == null ? other.getDuration() == null : this.getDuration().equals(other.getDuration()))
            && (this.getQuestion() == null ? other.getQuestion() == null : this.getQuestion().equals(other.getQuestion()))
            && (this.getAnswer() == null ? other.getAnswer() == null : this.getAnswer().equals(other.getAnswer()))
            && (this.getEvaluate() == null ? other.getEvaluate() == null : this.getEvaluate().equals(other.getEvaluate()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_evaluate
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getID() == null) ? 0 : getID().hashCode());
        result = prime * result + ((getDeptID() == null) ? 0 : getDeptID().hashCode());
        result = prime * result + ((getDeptName() == null) ? 0 : getDeptName().hashCode());
        result = prime * result + ((getWindowNo() == null) ? 0 : getWindowNo().hashCode());
        result = prime * result + ((getStaffID() == null) ? 0 : getStaffID().hashCode());
        result = prime * result + ((getStaffName() == null) ? 0 : getStaffName().hashCode());
        result = prime * result + ((getCustName() == null) ? 0 : getCustName().hashCode());
        result = prime * result + ((getCustMobile() == null) ? 0 : getCustMobile().hashCode());
        result = prime * result + ((getItemID() == null) ? 0 : getItemID().hashCode());
        result = prime * result + ((getItemName() == null) ? 0 : getItemName().hashCode());
        result = prime * result + ((getCreateDate() == null) ? 0 : getCreateDate().hashCode());
        result = prime * result + ((getBeginTime() == null) ? 0 : getBeginTime().hashCode());
        result = prime * result + ((getEndTime() == null) ? 0 : getEndTime().hashCode());
        result = prime * result + ((getDuration() == null) ? 0 : getDuration().hashCode());
        result = prime * result + ((getQuestion() == null) ? 0 : getQuestion().hashCode());
        result = prime * result + ((getAnswer() == null) ? 0 : getAnswer().hashCode());
        result = prime * result + ((getEvaluate() == null) ? 0 : getEvaluate().hashCode());
        return result;
    }
}