package com.btjf.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class EvaluateExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_evaluate
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_evaluate
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_evaluate
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_evaluate
     *
     * @mbg.generated
     */
    public EvaluateExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_evaluate
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_evaluate
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_evaluate
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_evaluate
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_evaluate
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_evaluate
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_evaluate
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_evaluate
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_evaluate
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_evaluate
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_evaluate
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andIDIsNull() {
            addCriterion("FID is null");
            return (Criteria) this;
        }

        public Criteria andIDIsNotNull() {
            addCriterion("FID is not null");
            return (Criteria) this;
        }

        public Criteria andIDEqualTo(Integer value) {
            addCriterion("FID =", value, "ID");
            return (Criteria) this;
        }

        public Criteria andIDNotEqualTo(Integer value) {
            addCriterion("FID <>", value, "ID");
            return (Criteria) this;
        }

        public Criteria andIDGreaterThan(Integer value) {
            addCriterion("FID >", value, "ID");
            return (Criteria) this;
        }

        public Criteria andIDGreaterThanOrEqualTo(Integer value) {
            addCriterion("FID >=", value, "ID");
            return (Criteria) this;
        }

        public Criteria andIDLessThan(Integer value) {
            addCriterion("FID <", value, "ID");
            return (Criteria) this;
        }

        public Criteria andIDLessThanOrEqualTo(Integer value) {
            addCriterion("FID <=", value, "ID");
            return (Criteria) this;
        }

        public Criteria andIDIn(List<Integer> values) {
            addCriterion("FID in", values, "ID");
            return (Criteria) this;
        }

        public Criteria andIDNotIn(List<Integer> values) {
            addCriterion("FID not in", values, "ID");
            return (Criteria) this;
        }

        public Criteria andIDBetween(Integer value1, Integer value2) {
            addCriterion("FID between", value1, value2, "ID");
            return (Criteria) this;
        }

        public Criteria andIDNotBetween(Integer value1, Integer value2) {
            addCriterion("FID not between", value1, value2, "ID");
            return (Criteria) this;
        }

        public Criteria andDeptIDIsNull() {
            addCriterion("FDeptID is null");
            return (Criteria) this;
        }

        public Criteria andDeptIDIsNotNull() {
            addCriterion("FDeptID is not null");
            return (Criteria) this;
        }

        public Criteria andDeptIDEqualTo(Integer value) {
            addCriterion("FDeptID =", value, "deptID");
            return (Criteria) this;
        }

        public Criteria andDeptIDNotEqualTo(Integer value) {
            addCriterion("FDeptID <>", value, "deptID");
            return (Criteria) this;
        }

        public Criteria andDeptIDGreaterThan(Integer value) {
            addCriterion("FDeptID >", value, "deptID");
            return (Criteria) this;
        }

        public Criteria andDeptIDGreaterThanOrEqualTo(Integer value) {
            addCriterion("FDeptID >=", value, "deptID");
            return (Criteria) this;
        }

        public Criteria andDeptIDLessThan(Integer value) {
            addCriterion("FDeptID <", value, "deptID");
            return (Criteria) this;
        }

        public Criteria andDeptIDLessThanOrEqualTo(Integer value) {
            addCriterion("FDeptID <=", value, "deptID");
            return (Criteria) this;
        }

        public Criteria andDeptIDIn(List<Integer> values) {
            addCriterion("FDeptID in", values, "deptID");
            return (Criteria) this;
        }

        public Criteria andDeptIDNotIn(List<Integer> values) {
            addCriterion("FDeptID not in", values, "deptID");
            return (Criteria) this;
        }

        public Criteria andDeptIDBetween(Integer value1, Integer value2) {
            addCriterion("FDeptID between", value1, value2, "deptID");
            return (Criteria) this;
        }

        public Criteria andDeptIDNotBetween(Integer value1, Integer value2) {
            addCriterion("FDeptID not between", value1, value2, "deptID");
            return (Criteria) this;
        }

        public Criteria andDeptNameIsNull() {
            addCriterion("FDeptName is null");
            return (Criteria) this;
        }

        public Criteria andDeptNameIsNotNull() {
            addCriterion("FDeptName is not null");
            return (Criteria) this;
        }

        public Criteria andDeptNameEqualTo(String value) {
            addCriterion("FDeptName =", value, "deptName");
            return (Criteria) this;
        }

        public Criteria andDeptNameNotEqualTo(String value) {
            addCriterion("FDeptName <>", value, "deptName");
            return (Criteria) this;
        }

        public Criteria andDeptNameGreaterThan(String value) {
            addCriterion("FDeptName >", value, "deptName");
            return (Criteria) this;
        }

        public Criteria andDeptNameGreaterThanOrEqualTo(String value) {
            addCriterion("FDeptName >=", value, "deptName");
            return (Criteria) this;
        }

        public Criteria andDeptNameLessThan(String value) {
            addCriterion("FDeptName <", value, "deptName");
            return (Criteria) this;
        }

        public Criteria andDeptNameLessThanOrEqualTo(String value) {
            addCriterion("FDeptName <=", value, "deptName");
            return (Criteria) this;
        }

        public Criteria andDeptNameLike(String value) {
            addCriterion("FDeptName like", value, "deptName");
            return (Criteria) this;
        }

        public Criteria andDeptNameNotLike(String value) {
            addCriterion("FDeptName not like", value, "deptName");
            return (Criteria) this;
        }

        public Criteria andDeptNameIn(List<String> values) {
            addCriterion("FDeptName in", values, "deptName");
            return (Criteria) this;
        }

        public Criteria andDeptNameNotIn(List<String> values) {
            addCriterion("FDeptName not in", values, "deptName");
            return (Criteria) this;
        }

        public Criteria andDeptNameBetween(String value1, String value2) {
            addCriterion("FDeptName between", value1, value2, "deptName");
            return (Criteria) this;
        }

        public Criteria andDeptNameNotBetween(String value1, String value2) {
            addCriterion("FDeptName not between", value1, value2, "deptName");
            return (Criteria) this;
        }

        public Criteria andCenterIdIsNull() {
            addCriterion("FCenterId is null");
            return (Criteria) this;
        }

        public Criteria andCenterIdIsNotNull() {
            addCriterion("FCenterId is not null");
            return (Criteria) this;
        }

        public Criteria andCenterIdEqualTo(String value) {
            addCriterion("FCenterId =", value, "centerId");
            return (Criteria) this;
        }

        public Criteria andCenterIdNotEqualTo(String value) {
            addCriterion("FCenterId <>", value, "centerId");
            return (Criteria) this;
        }

        public Criteria andCenterIdGreaterThan(String value) {
            addCriterion("FCenterId >", value, "centerId");
            return (Criteria) this;
        }

        public Criteria andCenterIdGreaterThanOrEqualTo(String value) {
            addCriterion("FCenterId >=", value, "centerId");
            return (Criteria) this;
        }

        public Criteria andCenterIdLessThan(String value) {
            addCriterion("FCenterId <", value, "centerId");
            return (Criteria) this;
        }

        public Criteria andCenterIdLessThanOrEqualTo(String value) {
            addCriterion("FCenterId <=", value, "centerId");
            return (Criteria) this;
        }

        public Criteria andCenterIdLike(String value) {
            addCriterion("FCenterId like", value, "centerId");
            return (Criteria) this;
        }

        public Criteria andCenterIdNotLike(String value) {
            addCriterion("FCenterId not like", value, "centerId");
            return (Criteria) this;
        }

        public Criteria andCenterIdIn(List<String> values) {
            addCriterion("FCenterId in", values, "centerId");
            return (Criteria) this;
        }

        public Criteria andCenterIdNotIn(List<String> values) {
            addCriterion("FCenterId not in", values, "centerId");
            return (Criteria) this;
        }

        public Criteria andCenterIdBetween(String value1, String value2) {
            addCriterion("FCenterId between", value1, value2, "centerId");
            return (Criteria) this;
        }

        public Criteria andCenterIdNotBetween(String value1, String value2) {
            addCriterion("FCenterId not between", value1, value2, "centerId");
            return (Criteria) this;
        }

        public Criteria andWindowIdIsNull() {
            addCriterion("FWindowId is null");
            return (Criteria) this;
        }

        public Criteria andWindowIdIsNotNull() {
            addCriterion("FWindowId is not null");
            return (Criteria) this;
        }

        public Criteria andWindowIdEqualTo(String value) {
            addCriterion("FWindowId =", value, "windowId");
            return (Criteria) this;
        }

        public Criteria andWindowIdNotEqualTo(String value) {
            addCriterion("FWindowId <>", value, "windowId");
            return (Criteria) this;
        }

        public Criteria andWindowIdGreaterThan(String value) {
            addCriterion("FWindowId >", value, "windowId");
            return (Criteria) this;
        }

        public Criteria andWindowIdGreaterThanOrEqualTo(String value) {
            addCriterion("FWindowId >=", value, "windowId");
            return (Criteria) this;
        }

        public Criteria andWindowIdLessThan(String value) {
            addCriterion("FWindowId <", value, "windowId");
            return (Criteria) this;
        }

        public Criteria andWindowIdLessThanOrEqualTo(String value) {
            addCriterion("FWindowId <=", value, "windowId");
            return (Criteria) this;
        }

        public Criteria andWindowIdLike(String value) {
            addCriterion("FWindowId like", value, "windowId");
            return (Criteria) this;
        }

        public Criteria andWindowIdNotLike(String value) {
            addCriterion("FWindowId not like", value, "windowId");
            return (Criteria) this;
        }

        public Criteria andWindowIdIn(List<String> values) {
            addCriterion("FWindowId in", values, "windowId");
            return (Criteria) this;
        }

        public Criteria andWindowIdNotIn(List<String> values) {
            addCriterion("FWindowId not in", values, "windowId");
            return (Criteria) this;
        }

        public Criteria andWindowIdBetween(String value1, String value2) {
            addCriterion("FWindowId between", value1, value2, "windowId");
            return (Criteria) this;
        }

        public Criteria andWindowIdNotBetween(String value1, String value2) {
            addCriterion("FWindowId not between", value1, value2, "windowId");
            return (Criteria) this;
        }

        public Criteria andStaffIDIsNull() {
            addCriterion("FStaffID is null");
            return (Criteria) this;
        }

        public Criteria andStaffIDIsNotNull() {
            addCriterion("FStaffID is not null");
            return (Criteria) this;
        }

        public Criteria andStaffIDEqualTo(String value) {
            addCriterion("FStaffID =", value, "staffID");
            return (Criteria) this;
        }

        public Criteria andStaffIDNotEqualTo(String value) {
            addCriterion("FStaffID <>", value, "staffID");
            return (Criteria) this;
        }

        public Criteria andStaffIDGreaterThan(String value) {
            addCriterion("FStaffID >", value, "staffID");
            return (Criteria) this;
        }

        public Criteria andStaffIDGreaterThanOrEqualTo(String value) {
            addCriterion("FStaffID >=", value, "staffID");
            return (Criteria) this;
        }

        public Criteria andStaffIDLessThan(String value) {
            addCriterion("FStaffID <", value, "staffID");
            return (Criteria) this;
        }

        public Criteria andStaffIDLessThanOrEqualTo(String value) {
            addCriterion("FStaffID <=", value, "staffID");
            return (Criteria) this;
        }

        public Criteria andStaffIDLike(String value) {
            addCriterion("FStaffID like", value, "staffID");
            return (Criteria) this;
        }

        public Criteria andStaffIDNotLike(String value) {
            addCriterion("FStaffID not like", value, "staffID");
            return (Criteria) this;
        }

        public Criteria andStaffIDIn(List<String> values) {
            addCriterion("FStaffID in", values, "staffID");
            return (Criteria) this;
        }

        public Criteria andStaffIDNotIn(List<String> values) {
            addCriterion("FStaffID not in", values, "staffID");
            return (Criteria) this;
        }

        public Criteria andStaffIDBetween(String value1, String value2) {
            addCriterion("FStaffID between", value1, value2, "staffID");
            return (Criteria) this;
        }

        public Criteria andStaffIDNotBetween(String value1, String value2) {
            addCriterion("FStaffID not between", value1, value2, "staffID");
            return (Criteria) this;
        }

        public Criteria andStaffNameIsNull() {
            addCriterion("FStaffName is null");
            return (Criteria) this;
        }

        public Criteria andStaffNameIsNotNull() {
            addCriterion("FStaffName is not null");
            return (Criteria) this;
        }

        public Criteria andStaffNameEqualTo(String value) {
            addCriterion("FStaffName =", value, "staffName");
            return (Criteria) this;
        }

        public Criteria andStaffNameNotEqualTo(String value) {
            addCriterion("FStaffName <>", value, "staffName");
            return (Criteria) this;
        }

        public Criteria andStaffNameGreaterThan(String value) {
            addCriterion("FStaffName >", value, "staffName");
            return (Criteria) this;
        }

        public Criteria andStaffNameGreaterThanOrEqualTo(String value) {
            addCriterion("FStaffName >=", value, "staffName");
            return (Criteria) this;
        }

        public Criteria andStaffNameLessThan(String value) {
            addCriterion("FStaffName <", value, "staffName");
            return (Criteria) this;
        }

        public Criteria andStaffNameLessThanOrEqualTo(String value) {
            addCriterion("FStaffName <=", value, "staffName");
            return (Criteria) this;
        }

        public Criteria andStaffNameLike(String value) {
            addCriterion("FStaffName like", value, "staffName");
            return (Criteria) this;
        }

        public Criteria andStaffNameNotLike(String value) {
            addCriterion("FStaffName not like", value, "staffName");
            return (Criteria) this;
        }

        public Criteria andStaffNameIn(List<String> values) {
            addCriterion("FStaffName in", values, "staffName");
            return (Criteria) this;
        }

        public Criteria andStaffNameNotIn(List<String> values) {
            addCriterion("FStaffName not in", values, "staffName");
            return (Criteria) this;
        }

        public Criteria andStaffNameBetween(String value1, String value2) {
            addCriterion("FStaffName between", value1, value2, "staffName");
            return (Criteria) this;
        }

        public Criteria andStaffNameNotBetween(String value1, String value2) {
            addCriterion("FStaffName not between", value1, value2, "staffName");
            return (Criteria) this;
        }

        public Criteria andCallCodeIsNull() {
            addCriterion("FCallCode is null");
            return (Criteria) this;
        }

        public Criteria andCallCodeIsNotNull() {
            addCriterion("FCallCode is not null");
            return (Criteria) this;
        }

        public Criteria andCallCodeEqualTo(String value) {
            addCriterion("FCallCode =", value, "callCode");
            return (Criteria) this;
        }

        public Criteria andCallCodeNotEqualTo(String value) {
            addCriterion("FCallCode <>", value, "callCode");
            return (Criteria) this;
        }

        public Criteria andCallCodeGreaterThan(String value) {
            addCriterion("FCallCode >", value, "callCode");
            return (Criteria) this;
        }

        public Criteria andCallCodeGreaterThanOrEqualTo(String value) {
            addCriterion("FCallCode >=", value, "callCode");
            return (Criteria) this;
        }

        public Criteria andCallCodeLessThan(String value) {
            addCriterion("FCallCode <", value, "callCode");
            return (Criteria) this;
        }

        public Criteria andCallCodeLessThanOrEqualTo(String value) {
            addCriterion("FCallCode <=", value, "callCode");
            return (Criteria) this;
        }

        public Criteria andCallCodeLike(String value) {
            addCriterion("FCallCode like", value, "callCode");
            return (Criteria) this;
        }

        public Criteria andCallCodeNotLike(String value) {
            addCriterion("FCallCode not like", value, "callCode");
            return (Criteria) this;
        }

        public Criteria andCallCodeIn(List<String> values) {
            addCriterion("FCallCode in", values, "callCode");
            return (Criteria) this;
        }

        public Criteria andCallCodeNotIn(List<String> values) {
            addCriterion("FCallCode not in", values, "callCode");
            return (Criteria) this;
        }

        public Criteria andCallCodeBetween(String value1, String value2) {
            addCriterion("FCallCode between", value1, value2, "callCode");
            return (Criteria) this;
        }

        public Criteria andCallCodeNotBetween(String value1, String value2) {
            addCriterion("FCallCode not between", value1, value2, "callCode");
            return (Criteria) this;
        }

        public Criteria andCustNameIsNull() {
            addCriterion("FCustName is null");
            return (Criteria) this;
        }

        public Criteria andCustNameIsNotNull() {
            addCriterion("FCustName is not null");
            return (Criteria) this;
        }

        public Criteria andCustNameEqualTo(String value) {
            addCriterion("FCustName =", value, "custName");
            return (Criteria) this;
        }

        public Criteria andCustNameNotEqualTo(String value) {
            addCriterion("FCustName <>", value, "custName");
            return (Criteria) this;
        }

        public Criteria andCustNameGreaterThan(String value) {
            addCriterion("FCustName >", value, "custName");
            return (Criteria) this;
        }

        public Criteria andCustNameGreaterThanOrEqualTo(String value) {
            addCriterion("FCustName >=", value, "custName");
            return (Criteria) this;
        }

        public Criteria andCustNameLessThan(String value) {
            addCriterion("FCustName <", value, "custName");
            return (Criteria) this;
        }

        public Criteria andCustNameLessThanOrEqualTo(String value) {
            addCriterion("FCustName <=", value, "custName");
            return (Criteria) this;
        }

        public Criteria andCustNameLike(String value) {
            addCriterion("FCustName like", value, "custName");
            return (Criteria) this;
        }

        public Criteria andCustNameNotLike(String value) {
            addCriterion("FCustName not like", value, "custName");
            return (Criteria) this;
        }

        public Criteria andCustNameIn(List<String> values) {
            addCriterion("FCustName in", values, "custName");
            return (Criteria) this;
        }

        public Criteria andCustNameNotIn(List<String> values) {
            addCriterion("FCustName not in", values, "custName");
            return (Criteria) this;
        }

        public Criteria andCustNameBetween(String value1, String value2) {
            addCriterion("FCustName between", value1, value2, "custName");
            return (Criteria) this;
        }

        public Criteria andCustNameNotBetween(String value1, String value2) {
            addCriterion("FCustName not between", value1, value2, "custName");
            return (Criteria) this;
        }

        public Criteria andCustMobileIsNull() {
            addCriterion("FCustMobile is null");
            return (Criteria) this;
        }

        public Criteria andCustMobileIsNotNull() {
            addCriterion("FCustMobile is not null");
            return (Criteria) this;
        }

        public Criteria andCustMobileEqualTo(String value) {
            addCriterion("FCustMobile =", value, "custMobile");
            return (Criteria) this;
        }

        public Criteria andCustMobileNotEqualTo(String value) {
            addCriterion("FCustMobile <>", value, "custMobile");
            return (Criteria) this;
        }

        public Criteria andCustMobileGreaterThan(String value) {
            addCriterion("FCustMobile >", value, "custMobile");
            return (Criteria) this;
        }

        public Criteria andCustMobileGreaterThanOrEqualTo(String value) {
            addCriterion("FCustMobile >=", value, "custMobile");
            return (Criteria) this;
        }

        public Criteria andCustMobileLessThan(String value) {
            addCriterion("FCustMobile <", value, "custMobile");
            return (Criteria) this;
        }

        public Criteria andCustMobileLessThanOrEqualTo(String value) {
            addCriterion("FCustMobile <=", value, "custMobile");
            return (Criteria) this;
        }

        public Criteria andCustMobileLike(String value) {
            addCriterion("FCustMobile like", value, "custMobile");
            return (Criteria) this;
        }

        public Criteria andCustMobileNotLike(String value) {
            addCriterion("FCustMobile not like", value, "custMobile");
            return (Criteria) this;
        }

        public Criteria andCustMobileIn(List<String> values) {
            addCriterion("FCustMobile in", values, "custMobile");
            return (Criteria) this;
        }

        public Criteria andCustMobileNotIn(List<String> values) {
            addCriterion("FCustMobile not in", values, "custMobile");
            return (Criteria) this;
        }

        public Criteria andCustMobileBetween(String value1, String value2) {
            addCriterion("FCustMobile between", value1, value2, "custMobile");
            return (Criteria) this;
        }

        public Criteria andCustMobileNotBetween(String value1, String value2) {
            addCriterion("FCustMobile not between", value1, value2, "custMobile");
            return (Criteria) this;
        }

        public Criteria andItemIDIsNull() {
            addCriterion("FItemID is null");
            return (Criteria) this;
        }

        public Criteria andItemIDIsNotNull() {
            addCriterion("FItemID is not null");
            return (Criteria) this;
        }

        public Criteria andItemIDEqualTo(Integer value) {
            addCriterion("FItemID =", value, "itemID");
            return (Criteria) this;
        }

        public Criteria andItemIDNotEqualTo(Integer value) {
            addCriterion("FItemID <>", value, "itemID");
            return (Criteria) this;
        }

        public Criteria andItemIDGreaterThan(Integer value) {
            addCriterion("FItemID >", value, "itemID");
            return (Criteria) this;
        }

        public Criteria andItemIDGreaterThanOrEqualTo(Integer value) {
            addCriterion("FItemID >=", value, "itemID");
            return (Criteria) this;
        }

        public Criteria andItemIDLessThan(Integer value) {
            addCriterion("FItemID <", value, "itemID");
            return (Criteria) this;
        }

        public Criteria andItemIDLessThanOrEqualTo(Integer value) {
            addCriterion("FItemID <=", value, "itemID");
            return (Criteria) this;
        }

        public Criteria andItemIDIn(List<Integer> values) {
            addCriterion("FItemID in", values, "itemID");
            return (Criteria) this;
        }

        public Criteria andItemIDNotIn(List<Integer> values) {
            addCriterion("FItemID not in", values, "itemID");
            return (Criteria) this;
        }

        public Criteria andItemIDBetween(Integer value1, Integer value2) {
            addCriterion("FItemID between", value1, value2, "itemID");
            return (Criteria) this;
        }

        public Criteria andItemIDNotBetween(Integer value1, Integer value2) {
            addCriterion("FItemID not between", value1, value2, "itemID");
            return (Criteria) this;
        }

        public Criteria andItemNameIsNull() {
            addCriterion("FItemName is null");
            return (Criteria) this;
        }

        public Criteria andItemNameIsNotNull() {
            addCriterion("FItemName is not null");
            return (Criteria) this;
        }

        public Criteria andItemNameEqualTo(String value) {
            addCriterion("FItemName =", value, "itemName");
            return (Criteria) this;
        }

        public Criteria andItemNameNotEqualTo(String value) {
            addCriterion("FItemName <>", value, "itemName");
            return (Criteria) this;
        }

        public Criteria andItemNameGreaterThan(String value) {
            addCriterion("FItemName >", value, "itemName");
            return (Criteria) this;
        }

        public Criteria andItemNameGreaterThanOrEqualTo(String value) {
            addCriterion("FItemName >=", value, "itemName");
            return (Criteria) this;
        }

        public Criteria andItemNameLessThan(String value) {
            addCriterion("FItemName <", value, "itemName");
            return (Criteria) this;
        }

        public Criteria andItemNameLessThanOrEqualTo(String value) {
            addCriterion("FItemName <=", value, "itemName");
            return (Criteria) this;
        }

        public Criteria andItemNameLike(String value) {
            addCriterion("FItemName like", value, "itemName");
            return (Criteria) this;
        }

        public Criteria andItemNameNotLike(String value) {
            addCriterion("FItemName not like", value, "itemName");
            return (Criteria) this;
        }

        public Criteria andItemNameIn(List<String> values) {
            addCriterion("FItemName in", values, "itemName");
            return (Criteria) this;
        }

        public Criteria andItemNameNotIn(List<String> values) {
            addCriterion("FItemName not in", values, "itemName");
            return (Criteria) this;
        }

        public Criteria andItemNameBetween(String value1, String value2) {
            addCriterion("FItemName between", value1, value2, "itemName");
            return (Criteria) this;
        }

        public Criteria andItemNameNotBetween(String value1, String value2) {
            addCriterion("FItemName not between", value1, value2, "itemName");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNull() {
            addCriterion("FCreateDate is null");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNotNull() {
            addCriterion("FCreateDate is not null");
            return (Criteria) this;
        }

        public Criteria andCreateDateEqualTo(Date value) {
            addCriterionForJDBCDate("FCreateDate =", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotEqualTo(Date value) {
            addCriterionForJDBCDate("FCreateDate <>", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThan(Date value) {
            addCriterionForJDBCDate("FCreateDate >", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("FCreateDate >=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThan(Date value) {
            addCriterionForJDBCDate("FCreateDate <", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("FCreateDate <=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateIn(List<Date> values) {
            addCriterionForJDBCDate("FCreateDate in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotIn(List<Date> values) {
            addCriterionForJDBCDate("FCreateDate not in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("FCreateDate between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("FCreateDate not between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andBeginTimeIsNull() {
            addCriterion("FBeginTime is null");
            return (Criteria) this;
        }

        public Criteria andBeginTimeIsNotNull() {
            addCriterion("FBeginTime is not null");
            return (Criteria) this;
        }

        public Criteria andBeginTimeEqualTo(Date value) {
            addCriterion("FBeginTime =", value, "beginTime");
            return (Criteria) this;
        }

        public Criteria andBeginTimeNotEqualTo(Date value) {
            addCriterion("FBeginTime <>", value, "beginTime");
            return (Criteria) this;
        }

        public Criteria andBeginTimeGreaterThan(Date value) {
            addCriterion("FBeginTime >", value, "beginTime");
            return (Criteria) this;
        }

        public Criteria andBeginTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("FBeginTime >=", value, "beginTime");
            return (Criteria) this;
        }

        public Criteria andBeginTimeLessThan(Date value) {
            addCriterion("FBeginTime <", value, "beginTime");
            return (Criteria) this;
        }

        public Criteria andBeginTimeLessThanOrEqualTo(Date value) {
            addCriterion("FBeginTime <=", value, "beginTime");
            return (Criteria) this;
        }

        public Criteria andBeginTimeIn(List<Date> values) {
            addCriterion("FBeginTime in", values, "beginTime");
            return (Criteria) this;
        }

        public Criteria andBeginTimeNotIn(List<Date> values) {
            addCriterion("FBeginTime not in", values, "beginTime");
            return (Criteria) this;
        }

        public Criteria andBeginTimeBetween(Date value1, Date value2) {
            addCriterion("FBeginTime between", value1, value2, "beginTime");
            return (Criteria) this;
        }

        public Criteria andBeginTimeNotBetween(Date value1, Date value2) {
            addCriterion("FBeginTime not between", value1, value2, "beginTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeIsNull() {
            addCriterion("FEndTime is null");
            return (Criteria) this;
        }

        public Criteria andEndTimeIsNotNull() {
            addCriterion("FEndTime is not null");
            return (Criteria) this;
        }

        public Criteria andEndTimeEqualTo(Date value) {
            addCriterion("FEndTime =", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeNotEqualTo(Date value) {
            addCriterion("FEndTime <>", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeGreaterThan(Date value) {
            addCriterion("FEndTime >", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("FEndTime >=", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeLessThan(Date value) {
            addCriterion("FEndTime <", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeLessThanOrEqualTo(Date value) {
            addCriterion("FEndTime <=", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeIn(List<Date> values) {
            addCriterion("FEndTime in", values, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeNotIn(List<Date> values) {
            addCriterion("FEndTime not in", values, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeBetween(Date value1, Date value2) {
            addCriterion("FEndTime between", value1, value2, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeNotBetween(Date value1, Date value2) {
            addCriterion("FEndTime not between", value1, value2, "endTime");
            return (Criteria) this;
        }

        public Criteria andDurationIsNull() {
            addCriterion("FDuration is null");
            return (Criteria) this;
        }

        public Criteria andDurationIsNotNull() {
            addCriterion("FDuration is not null");
            return (Criteria) this;
        }

        public Criteria andDurationEqualTo(Integer value) {
            addCriterion("FDuration =", value, "duration");
            return (Criteria) this;
        }

        public Criteria andDurationNotEqualTo(Integer value) {
            addCriterion("FDuration <>", value, "duration");
            return (Criteria) this;
        }

        public Criteria andDurationGreaterThan(Integer value) {
            addCriterion("FDuration >", value, "duration");
            return (Criteria) this;
        }

        public Criteria andDurationGreaterThanOrEqualTo(Integer value) {
            addCriterion("FDuration >=", value, "duration");
            return (Criteria) this;
        }

        public Criteria andDurationLessThan(Integer value) {
            addCriterion("FDuration <", value, "duration");
            return (Criteria) this;
        }

        public Criteria andDurationLessThanOrEqualTo(Integer value) {
            addCriterion("FDuration <=", value, "duration");
            return (Criteria) this;
        }

        public Criteria andDurationIn(List<Integer> values) {
            addCriterion("FDuration in", values, "duration");
            return (Criteria) this;
        }

        public Criteria andDurationNotIn(List<Integer> values) {
            addCriterion("FDuration not in", values, "duration");
            return (Criteria) this;
        }

        public Criteria andDurationBetween(Integer value1, Integer value2) {
            addCriterion("FDuration between", value1, value2, "duration");
            return (Criteria) this;
        }

        public Criteria andDurationNotBetween(Integer value1, Integer value2) {
            addCriterion("FDuration not between", value1, value2, "duration");
            return (Criteria) this;
        }

        public Criteria andQuestionIsNull() {
            addCriterion("FQuestion is null");
            return (Criteria) this;
        }

        public Criteria andQuestionIsNotNull() {
            addCriterion("FQuestion is not null");
            return (Criteria) this;
        }

        public Criteria andQuestionEqualTo(String value) {
            addCriterion("FQuestion =", value, "question");
            return (Criteria) this;
        }

        public Criteria andQuestionNotEqualTo(String value) {
            addCriterion("FQuestion <>", value, "question");
            return (Criteria) this;
        }

        public Criteria andQuestionGreaterThan(String value) {
            addCriterion("FQuestion >", value, "question");
            return (Criteria) this;
        }

        public Criteria andQuestionGreaterThanOrEqualTo(String value) {
            addCriterion("FQuestion >=", value, "question");
            return (Criteria) this;
        }

        public Criteria andQuestionLessThan(String value) {
            addCriterion("FQuestion <", value, "question");
            return (Criteria) this;
        }

        public Criteria andQuestionLessThanOrEqualTo(String value) {
            addCriterion("FQuestion <=", value, "question");
            return (Criteria) this;
        }

        public Criteria andQuestionLike(String value) {
            addCriterion("FQuestion like", value, "question");
            return (Criteria) this;
        }

        public Criteria andQuestionNotLike(String value) {
            addCriterion("FQuestion not like", value, "question");
            return (Criteria) this;
        }

        public Criteria andQuestionIn(List<String> values) {
            addCriterion("FQuestion in", values, "question");
            return (Criteria) this;
        }

        public Criteria andQuestionNotIn(List<String> values) {
            addCriterion("FQuestion not in", values, "question");
            return (Criteria) this;
        }

        public Criteria andQuestionBetween(String value1, String value2) {
            addCriterion("FQuestion between", value1, value2, "question");
            return (Criteria) this;
        }

        public Criteria andQuestionNotBetween(String value1, String value2) {
            addCriterion("FQuestion not between", value1, value2, "question");
            return (Criteria) this;
        }

        public Criteria andAnswerIsNull() {
            addCriterion("FAnswer is null");
            return (Criteria) this;
        }

        public Criteria andAnswerIsNotNull() {
            addCriterion("FAnswer is not null");
            return (Criteria) this;
        }

        public Criteria andAnswerEqualTo(Integer value) {
            addCriterion("FAnswer =", value, "answer");
            return (Criteria) this;
        }

        public Criteria andAnswerNotEqualTo(Integer value) {
            addCriterion("FAnswer <>", value, "answer");
            return (Criteria) this;
        }

        public Criteria andAnswerGreaterThan(Integer value) {
            addCriterion("FAnswer >", value, "answer");
            return (Criteria) this;
        }

        public Criteria andAnswerGreaterThanOrEqualTo(Integer value) {
            addCriterion("FAnswer >=", value, "answer");
            return (Criteria) this;
        }

        public Criteria andAnswerLessThan(Integer value) {
            addCriterion("FAnswer <", value, "answer");
            return (Criteria) this;
        }

        public Criteria andAnswerLessThanOrEqualTo(Integer value) {
            addCriterion("FAnswer <=", value, "answer");
            return (Criteria) this;
        }

        public Criteria andAnswerIn(List<Integer> values) {
            addCriterion("FAnswer in", values, "answer");
            return (Criteria) this;
        }

        public Criteria andAnswerNotIn(List<Integer> values) {
            addCriterion("FAnswer not in", values, "answer");
            return (Criteria) this;
        }

        public Criteria andAnswerBetween(Integer value1, Integer value2) {
            addCriterion("FAnswer between", value1, value2, "answer");
            return (Criteria) this;
        }

        public Criteria andAnswerNotBetween(Integer value1, Integer value2) {
            addCriterion("FAnswer not between", value1, value2, "answer");
            return (Criteria) this;
        }

        public Criteria andEvaluateIsNull() {
            addCriterion("FEvaluate is null");
            return (Criteria) this;
        }

        public Criteria andEvaluateIsNotNull() {
            addCriterion("FEvaluate is not null");
            return (Criteria) this;
        }

        public Criteria andEvaluateEqualTo(Integer value) {
            addCriterion("FEvaluate =", value, "evaluate");
            return (Criteria) this;
        }

        public Criteria andEvaluateNotEqualTo(Integer value) {
            addCriterion("FEvaluate <>", value, "evaluate");
            return (Criteria) this;
        }

        public Criteria andEvaluateGreaterThan(Integer value) {
            addCriterion("FEvaluate >", value, "evaluate");
            return (Criteria) this;
        }

        public Criteria andEvaluateGreaterThanOrEqualTo(Integer value) {
            addCriterion("FEvaluate >=", value, "evaluate");
            return (Criteria) this;
        }

        public Criteria andEvaluateLessThan(Integer value) {
            addCriterion("FEvaluate <", value, "evaluate");
            return (Criteria) this;
        }

        public Criteria andEvaluateLessThanOrEqualTo(Integer value) {
            addCriterion("FEvaluate <=", value, "evaluate");
            return (Criteria) this;
        }

        public Criteria andEvaluateIn(List<Integer> values) {
            addCriterion("FEvaluate in", values, "evaluate");
            return (Criteria) this;
        }

        public Criteria andEvaluateNotIn(List<Integer> values) {
            addCriterion("FEvaluate not in", values, "evaluate");
            return (Criteria) this;
        }

        public Criteria andEvaluateBetween(Integer value1, Integer value2) {
            addCriterion("FEvaluate between", value1, value2, "evaluate");
            return (Criteria) this;
        }

        public Criteria andEvaluateNotBetween(Integer value1, Integer value2) {
            addCriterion("FEvaluate not between", value1, value2, "evaluate");
            return (Criteria) this;
        }

        public Criteria andDeptNameLikeInsensitive(String value) {
            addCriterion("upper(FDeptName) like", value.toUpperCase(), "deptName");
            return (Criteria) this;
        }

        public Criteria andCenterIdLikeInsensitive(String value) {
            addCriterion("upper(FCenterId) like", value.toUpperCase(), "centerId");
            return (Criteria) this;
        }

        public Criteria andWindowIdLikeInsensitive(String value) {
            addCriterion("upper(FWindowId) like", value.toUpperCase(), "windowId");
            return (Criteria) this;
        }

        public Criteria andStaffIDLikeInsensitive(String value) {
            addCriterion("upper(FStaffID) like", value.toUpperCase(), "staffID");
            return (Criteria) this;
        }

        public Criteria andStaffNameLikeInsensitive(String value) {
            addCriterion("upper(FStaffName) like", value.toUpperCase(), "staffName");
            return (Criteria) this;
        }

        public Criteria andCallCodeLikeInsensitive(String value) {
            addCriterion("upper(FCallCode) like", value.toUpperCase(), "callCode");
            return (Criteria) this;
        }

        public Criteria andCustNameLikeInsensitive(String value) {
            addCriterion("upper(FCustName) like", value.toUpperCase(), "custName");
            return (Criteria) this;
        }

        public Criteria andCustMobileLikeInsensitive(String value) {
            addCriterion("upper(FCustMobile) like", value.toUpperCase(), "custMobile");
            return (Criteria) this;
        }

        public Criteria andItemNameLikeInsensitive(String value) {
            addCriterion("upper(FItemName) like", value.toUpperCase(), "itemName");
            return (Criteria) this;
        }

        public Criteria andQuestionLikeInsensitive(String value) {
            addCriterion("upper(FQuestion) like", value.toUpperCase(), "question");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_evaluate
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_evaluate
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}